guitarchord.setTimbre(guitarchord.Timbre.Square50)
guitarchord.setDelay(120)
guitarchord.assignChord(guitarchord.ChordButton.Button1, guitarchord.Chord.C)
guitarchord.assignChord(guitarchord.ChordButton.Button2, guitarchord.Chord.G)
guitarchord.assignFrequencies(guitarchord.ChordButton.Button3, 220, 277, 330)
